// Code generated by goctl. DO NOT EDIT.
// Source: test.proto

package testrpc

import (
	"context"

	"cloud-native-zero/app/testApi/cmd/api/client/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	TestReq  = pb.TestReq
	TestResp = pb.TestResp

	TestRpc interface {
		Test(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestResp, error)
	}

	defaultTestRpc struct {
		cli zrpc.Client
	}
)

func NewTestRpc(cli zrpc.Client) TestRpc {
	return &defaultTestRpc{
		cli: cli,
	}
}

func (m *defaultTestRpc) Test(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestResp, error) {
	client := pb.NewTestRpcClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}
