// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Id int64 `form:"id"`
}

type Response struct {
	Message string `json:"message"`
}

type DbRequest struct {
	Id int64 `form:"id"`
}

type DbResponse struct {
	Message string `json:"message"`
}
